vich_uploader:
  db_driver: orm
  mappings:
    # This is an example configuration for an entity named "Evenement" that has a property named "image".
    post_image:
      uri_prefix: /image
      upload_destination: '%kernel.project_dir%/public/images/posts'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer