controllers:
    resource: ../src/Controller/
    type: attribute

# config/routes.yaml
accueil:
    path: /
    controller: App\Controller\DefaultController::index


front_post:
    path: /front/post
    controller: App\Controller\FrontPostController::index


post_index:
    path: /crudpost
    controller: App\Controller\CRUDPostController::index


# config/routes.yaml
commentaire_index:
    path: /crudcommentaire
    controller: App\Controller\CRUDCommentaireController::index

admin_home:
    path: /admin
    controller: App\Controller\AdminController::index

app_panier_index:
  path: /panier
  controller: App\Controller\PanierController::index


app_produit_index:
  path: /produit
  controller: App\Controller\ProduitController::index

app_stat_commentaire:
  path: /stat_commentaire
  controller: App\Controller\CRUDCommentaireController::statAction


app_stat_crud:
  path: /stat_post
  controller: App\Controller\CRUDPostController::statAction



