#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_produit_pdf:
    path: '/produit/{id}/pdf'
    controller: 'App\Controller\ProduitController::pdfAction'
    requirements:
        id: '\d+'